name: Vercel Preview Deploy

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

env:
  CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cypress
  PERCY_POSTINSTALL_BROWSER: true
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Restore Cypress Binary
        uses: actions/cache@v3
        with:
          path: .cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Application Dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn cypress version
          yarn cypress cache path
          yarn cypress cache list

      - name: Formatting
        run: yarn run lint:format

      - name: Lint Scripts
        run: yarn run lint:js

      - name: Lint Styles
        run: yarn run lint:css

      - name: Run Cypress Integration Tests
        run: yarn run test:integration:headless

      - name: Store Integration Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-artifacts
          retention-days: 5
          path: |
            cypress/screenshots/
            cypress/videos/

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy-artifacts
        run: |
          echo "DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Upsert Pull Request Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const COMMENT_PREFIX = 'Preview URL:';
            const commentBody = `${COMMENT_PREFIX} [${{ steps.deploy-artifacts.outputs.DEPLOY_URL }}](${{ steps.deploy-artifacts.outputs.DEPLOY_URL }})`;

            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const existingComment = comments.find((comment) => {
              return comment.body.startsWith(COMMENT_PREFIX);
            });

            if (existingComment) {
              return await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            }

            return await github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: commentBody,
            });

      - name: Create Deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.head_ref }}',
              environment: 'Preview',
              required_contexts: [],
              auto_merge: false,
            });

            return await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              state: 'success',
              environment_url: '${{ steps.deploy-artifacts.outputs.DEPLOY_URL }}',
            });

      - name: Run Cypress End-To-End Tests
        run: CYPRESS_BASE_URL=${{ steps.deploy-artifacts.outputs.DEPLOY_URL }} yarn run test:e2e:headless

      - name: Store End-To-End Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: end-to-end-test-artifacts
          retention-days: 5
          path: |
            cypress/screenshots/
            cypress/videos/
